import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Sidebar from './side-bar';
import Topbar from './top-bar';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import { SnackbarProvider } from '@/hooks/useSnackbar';
config.autoAddCss = false;

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SnackbarProvider>
          <div className="flex h-screen w-screen min-w-[1280px]">
            <Sidebar />
            <div className="flex w-[calc(100vw-280px)] flex-col">
              <Topbar />
              <div className="min-h-[calc(100vh-80px)] w-[calc(100vw-280px)] min-w-[1000px] overflow-y-auto bg-slate-50">
                {children}
              </div>
            </div>
          </div>
        </SnackbarProvider>
      </body>
    </html>
  );
}
